### ISSUE TITLE
Module resolution error after updating to `@datadog/browser-rum` 4.44.1

### ISSUE THREAD

**Issue by derekcicerone** [DataDog/browser-sdk#2330]
**Describe the bug**
Just updated to @datadog/browser-rum 4.44.1 and we're seeing this error when running unit tests:
```
Error: Jest: Got error running globalSetup - <redacted>/jestGlobalSetup.ts, reason: Cannot find module '@datadog/browser-worker/string'
Require stack:
- /home/runner/work/wonder/wonder/node_modules/@datadog/browser-rum/cjs/domain/segmentCollection/startDeflateWorker.js
- /home/runner/work/wonder/wonder/node_modules/@datadog/browser-rum/cjs/domain/segmentCollection/index.js
- /home/runner/work/wonder/wonder/node_modules/@datadog/browser-rum/cjs/boot/startRecording.js
- /home/runner/work/wonder/wonder/node_modules/@datadog/browser-rum/cjs/entries/main.js
```

**To Reproduce**
Install the latest release of `@datadog/browser-rum`.

**Expected behavior**
No module resolution errors.

**Comment by samc** [comment]
seeing the same thing with `esm` imports for any projects with a dependency graph in the range of `^4.x` for `@datadog/browser-rum`

**Comment by ngbrown** [comment]
When building a Remix application (which uses esbuild), I too had encountered this problem after updating to 4.44.1:

```
✘ [ERROR] Could not resolve "@datadog/browser-worker/string"

    node_modules/@datadog/browser-rum/esm/domain/segmentCollection/startDeflateWorker.js:2:29:
      2 │ import { workerString } from '@datadog/browser-worker/string';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Looking at the installed `@datadog/browser-worker` package in `node_modules` it makes no sense to import from `@datadog/browser-worker/string`. There is no folder or file at that location. I see that in the source in this repo, there is a `package.json` in the [`packages/worker/string` directory](https://github.com/DataDog/browser-sdk/tree/2dcd8db0712ceb688ed5157b1d73873ec5caed5b/packages/worker/string), but that isn't translating to anything in the published npm package.

It looks like these changes were introduced by #2319.

cc: @BenoitZugmeyer

**Comment by JuanGuerreroMp** [comment]
Same here in a react app: `

./node_modules/@datadog/browser-rum/esm/domain/segmentCollection/startDeflateWorker.js
--
13:14:23.627 | Module not found: Can't resolve '@datadog/browser-worker/string' in '/vercel/path0/node_modules/@datadog/browser-rum/esm/domain/segmentCollection'

`
Tested with different versions 4.44.0 and 4.35.0

**Comment by samc** [comment]
overall quite a bizarre set of library ergonomics, managed to get things working by running the `build-worker-string` build script locally, and copying over the nested `string` package. patch file for those interested:

https://gist.github.com/samc/03aa379b5872bce539f03caec4b39085

**Comment by samc** [comment]
overall a bizarre set of library imports / ergonomics, managed to get our Next front-ends back up and stable by running the package build script locally:

https://github.com/DataDog/browser-sdk/blob/2dcd8db0712ceb688ed5157b1d73873ec5caed5b/packages/worker/scripts/build-worker-string.js#L1-L11

that wasn't enough as the `cjs` bindings aren't generated via the webpack config, had to generate those ad-hoc. here's a patch for anyone that needs a quick fix:

https://gist.github.com/samc/03aa379b5872bce539f03caec4b39085

**Comment by bcaudan** [comment]
Hello,

Indeed, there is an issue on our side there.
We have identified the root cause and will come with a fix shortly.
You can use the 4.44.0 in the mean time.

Sorry for the trouble.

**Comment by bsatria** [comment]
this issue make my Dockerfile on gitlab cicd not working, tested in datadog/browser-rum 4.20^ version still have same problem.

**Comment by BenoitZugmeyer** [comment]
👋 Hello everyone,
New packages have been released. Please update to `v4.44.2` or later. Let us know if you still have any issue.
